email: 
password: 

server:
  port: 2333
  address: 127.0.0.1

plugins:
  youtube:
    oauth:
      enabled: true

lavalink:
  plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
        snapshot: false
  server:
    password: "8642"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: false
      local: false
    soundcloudSearchEnabled: true
  
logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
